# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night: minimal
  font: classic
  font_size: M

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'A highly-customizable Hugo academic resume theme powered by Wowchemy website builder.'
    twitter: 'wowchemy'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

footer:
  copyright:
    notice: '© {year} Zhicong Chen. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Contact (edit or remove options as required)

email: jssyczc@gmail.com
# phone: 888 888 88 88
address:
  street: M5013, 5/F, Run Run Shaw Creative Media Centre, 18 Tat Hong Avenue
  city: Kowloon
  region: Hong Kong SAR, China
  # postcode: '94305'
  country: Hong Kong
  country_code: HK
# coordinates:
#   latitude: '22.340172'
#   longitude: '114.1662723'
# directions: Enter Building 1 and take the stairs to Office 200 on Floor 2
# office_hours:
#   - 'Monday 10:00 to 13:00'
#   - 'Wednesday 09:00 to 10:00'
# appointment_url: 'https://calendly.com'
# contact_links:
#   - icon: twitter
#     icon_pack: fab
#     name: DM Me
#     link: 'https://twitter.com/Twitter'
#   - icon: skype
#     icon_pack: fab
#     name: Skype Me
#     link: 'skype:echo123?call'
#   - icon: keybase
#     icon_pack: fab
#     name: Chat on Keybase
#     link: 'https://keybase.io/'
#   - icon: comments
#     icon_pack: fas
#     name: Discuss on Forum
#     link: 'https://discourse.gohugo.io'

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: false
  diagram:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/zhicongchen/starter-hugo-academic'
    content_dir: content
    branch: master
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: master
    local_backend: false
  isotope:
    # Enable if you use the Portfolio widget or Publication filter
    enable: true
  academicons:
    enable: true

